; Cries indexes (see audio/cry_pointers.asm)
	const_def

; gen 1
	const CRY_NIDORAN_M
	const CRY_NIDORAN_F
	const CRY_SLOWPOKE
	const CRY_KANGASKHAN
	const CRY_CHARMANDER
	const CRY_GRIMER
	const CRY_VOLTORB
	const CRY_MUK
	const CRY_ODDISH
	const CRY_RAICHU
	const CRY_NIDOQUEEN
	const CRY_DIGLETT
	const CRY_SEEL
	const CRY_DROWZEE
	const CRY_PIDGEY
	const CRY_BULBASAUR
	const CRY_SPEAROW
	const CRY_RHYDON
	const CRY_GOLEM
	const CRY_BLASTOISE
	const CRY_PIDGEOTTO
	const CRY_WEEDLE
	const CRY_CATERPIE
	const CRY_EKANS
	const CRY_FEAROW
	const CRY_CLEFAIRY
	const CRY_VENONAT
	const CRY_LAPRAS
	const CRY_METAPOD
	const CRY_SQUIRTLE
	const CRY_PARAS
	const CRY_GROWLITHE
	const CRY_KRABBY
	const CRY_PSYDUCK
	const CRY_RATTATA
	const CRY_VILEPLUME
	const CRY_VULPIX
	const CRY_WEEPINBELL

; gen 2
	const CRY_MARILL
	const CRY_SPINARAK
	const CRY_TOGEPI
	const CRY_GIRAFARIG
	const CRY_RAIKOU
	const CRY_MAREEP
	const CRY_TOGETIC
	const CRY_HOOTHOOT
	const CRY_SENTRET
	const CRY_SLOWKING
	const CRY_CYNDAQUIL
	const CRY_CHIKORITA
	const CRY_TOTODILE
	const CRY_GLIGAR
	const CRY_CLEFFA
	const CRY_SLUGMA
	const CRY_LEDYBA
	const CRY_ENTEI
	const CRY_WOOPER
	const CRY_MANTINE
	const CRY_TYPHLOSION
	const CRY_NATU
	const CRY_TEDDIURSA
	const CRY_SUNFLORA
	const CRY_AMPHAROS
        const CRY_MAGCARGO
        const CRY_PICHU
        const CRY_AIPOM
        const CRY_DUNSPARCE
        const CRY_DONPHAN

; gen 3
        const CRY_POOCHYENA
	const CRY_MIGHTYENA
        const CRY_ZIGZAGOON
        const CRY_WINGULL
	const CRY_PELIPPER
        const CRY_RALTS
        const CRY_KIRLIA
        const CRY_GALLADE
        const CRY_SHROOMISH
	const CRY_BRELOOM
        const CRY_NINCADA
        const CRY_AZURILL
        const CRY_LATIAS
        const CRY_ARON
        const CRY_CARVANHA
        const CRY_WAILMER
        const CRY_NUMEL
        const CRY_SPOINK
        const CRY_SPINDA
        const CRY_TRAPINCH
        const CRY_SWABLU
        const CRY_ZANGOOSE
        const CRY_SEVIPER
        const CRY_FEEBAS
	const CRY_MILOTIC
        const CRY_KECLEON
        const CRY_SHUPPET
        const CRY_DUSKULL
        const CRY_TROPIUS
        const CRY_CHIMECHO
        const CRY_WYNAUT
        const CRY_SNORUNT
        const CRY_SPHEAL
        const CRY_RELICANTH
        const CRY_LUVDISC

        ; gen 4
        const CRY_SHINX
        const CRY_CHERUBI
        const CRY_CHATOT
        const CRY_RIOLU
        const CRY_CROAGUNK
        const CRY_CARNIVINE
        const CRY_FINNEON
        const CRY_ROTOM
        const CRY_PHIONE
        const CRY_FERROSEED
        const CRY_STUNFISK
        const CRY_PAWNIARD
        const CRY_ZORUA
        const CRY_SKRELP
        const CRY_CLAUNCHER
        const CRY_SYLVEON
        const CRY_PANCHAM
        const CRY_INKAY
        const CRY_NOIBAT
        const CRY_HONEDGE
        const CRY_GOOMY
        const CRY_ROCKRUFF
        const CRY_CUTIEFLY
        const CRY_PIKIPEK
        const CRY_MIMIKYU
        const CRY_SANDYGAST
        const CRY_SALANDIT
        const CRY_MAREANIE
        const CRY_TURTONATOR
        const CRY_DHELMISE
        const CRY_PINCURCHIN
        const CRY_CRAMORANT
        const CRY_BINACLE
        const CRY_APPLIN
        const CRY_GIMMIGHOUL
        const CRY_ANNIHILAPE
        const CRY_DUDUNSPARCE
        const CRY_FARIGIRAF
        const CRY_KINGAMBIT
        const CRY_DIPPLIN
        const CRY_CHARCADET
        const CRY_CLODSIRE
        const CRY_CURSOLA
        const CRY_PERRSERKER
        const CRY_SIRFETCHD
        const CRY_MRRIME
        const CRY_OBSTAGOON
        const CRY_OVERQWIL
        const CRY_SNEASLER
        const CRY_KLEAVOR
        const CRY_URSALUNA
        const CRY_WYRDEER
        const CRY_MARSHADOW
        const CRY_MELTAN
        const CRY_MELMETAL

DEF NUM_CRIES EQU const_value
