; wEventFlags bit flags

	const_def
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
; Johto Gym Leader TM gifts
; HMs (EVENT_GOT_HM07_WATERFALL is with the Johto itemballs)
        const EVENT_HM_01_CUT
        const EVENT_HM_02_FLY
        const EVENT_HM_03_SURF
        const EVENT_HM_04_STRENGTH
        const EVENT_HM_05_WHIRLPOOL
        const EVENT_HM_06_ROCK_SMASH
        const EVENT_HM_07_WATERFALL
        const EVENT_HM_08_DIVE
        const EVENT_HM_09_ROCK_CLIMB
; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
	const EVENT_GOT_SUPER_ROD
; Johto story events
	const EVENT_GOT_A_POKEMON_FROM_IVY
	const EVENT_GOT_CHARMANDER_FROM_IVY
	const EVENT_GOT_SQUIRTLE_FROM_IVY
	const EVENT_GOT_BULBASAUR_FROM_IVY
	const EVENT_GOT_PIKACHU_FROM_IVY
	const EVENT_GOT_EEVEE_FROM_IVY
	const EVENT_GOT_DRATINI_FROM_IVY
	const EVENT_IVYS_BASEMENT_OPENED
	const EVENT_MEET_SECRET_STARTER_REQS
	const EVENT_MET_CROSS_ON_VALENCIA
	const EVENT_GOT_TOWN_MAP
	const EVENT_PASSED_LORELEI_R49
	const EVENT_GOT_BALL_FROM_GUY_TANGELO
	const EVENT_TANGELO_GAVE_GRANDAUGHTER_STASH
	const EVENT_TANGELO_OLD_MAN_GIVEN_STASH
	const EVENT_TANGELO_OLD_MAN_SIDEQUEST_STARTED
	const EVENT_GOT_CYNDAQUIL_FROM_TANGELO
	const EVENT_BERRY_SELLER_PINKAN
	const EVENT_TALKED_TO_JUNGLE_GURU
	const EVENT_GOT_TOTODILE_FROM_TANGELO
	const EVENT_TALKED_TO_TANGELO_GENTLEMAN
	const EVENT_STARTED_OLD_ROD_SIDEQUEST
	const EVENT_OLD_ROD_SIDEQUEST_GIVEN_BAMBOO
	const EVENT_MIKAN_GYM_PLAYER_IS_FEMALE
	const EVENT_MIKAN_GYM_PLAYER_IS_MALE
	const EVENT_SENTA_LEAVES_GYM
	const EVENT_LUNA_HAS_A_ITEM_FOR_YOU
	const EVENT_GOT_CHIKORITA_FROM_MIKAN_THICKET
	const EVENT_TALKED_TO_FLOWER_GIRL
	const EVENT_MANDARIN_NORTH_MET_LOOKER
	const EVENT_MANDARIN_NORTH_ZORUA_BATTLE
	const EVENT_RATICATE_RADIO_VACATED
	const EVENT_RATICATE_RADIO_SWITCH_PRESSED
	const EVENT_GOT_CHARCOAL_FROM_GLASSBLOWER
	const EVENT_GOT_HARD_STONE_FROM_GLASSBLOWER
; Johto hidden items
	const EVENT_ROUTE_49_HIDDEN_POTION
	const EVENT_ROUTE_49_HIDDEN_STAR_PIECE
	const EVENT_ROUTE_49_NORTH_HIDDEN_BEACH_GLASS
	const EVENT_TANGELO_HIDDEN_BIG_MUSHROOM
	const EVENT_TANGELO_HIDDEN_TINY_MUSHROOM
	const EVENT_ROUTE_50_HIDDEN_POKE_BALL
	const EVENT_ROUTE_50_HIDDEN_PRETTY_SHELL
	const EVENT_ROUTE_50_HIDDEN_NET_BALL
	const EVENT_ROUTE_50_HIDDEN_FULL_HEAL
	const EVENT_ROUTE_50_HIDDEN_TINYMUSHROOM
	const EVENT_ROUTE_50_HIDDEN_SUPER_POTION
	const EVENT_TANGELO_MART_HIDDEN_PREMIER_BALL
	const EVENT_ROUTE_49_HIDDEN_REVIVE
	const EVENT_ROUTE_52_HIDDEN_GREAT_BALL
	const EVENT_ROUTE_52_HIDDEN_PEARL
	const EVENT_ROUTE_52_HIDDEN_BURN_HEAL
	const EVENT_MIKAN_THICKET_HIDDEN_TINY_BAMBOO_1
	const EVENT_MIKAN_THICKET_HIDDEN_TINY_BAMBOO_2
	const EVENT_MIKAN_THICKET_HIDDEN_TINY_BAMBOO_3
	const EVENT_MIKAN_THICKET_HIDDEN_BIG_BAMBOO_1
	const EVENT_MIKAN_THICKET_HIDDEN_BIG_BAMBOO_2
	const EVENT_MIKAN_THICKET_HIDDEN_NUGGET
	const EVENT_MIKAN_THICKET_HIDDEN_RARE_CANDY
	const EVENT_MIKAN_ISLAND_HIDDEN_REVIVE
	const EVENT_MIKAN_ISLAND_HIDDEN_SUPER_POTION
	const EVENT_MIKAN_RANCH_HIDDEN_REVIVE
	const EVENT_MIKAN_RANCH_HIDDEN_STICK
	const EVENT_MANDARIN_NORTH_HIDDEN_HYPER_POTION
	const EVENT_MANDARIN_NORTH_HIDDEN_DUSK_BALL
	const EVENT_RATICATE_RADIO_B1F_HIDDEN_ETHER
	const EVENT_RATICATE_RADIO_B2F_HIDDEN_BLACKGLASSES
	const EVENT_SUNBURST_HIDDEN_RARE_CANDY
	const EVENT_SUNBURST_HIDDEN_PRETTY_SHELL
	const EVENT_SUNBURST_HIDDEN_BIG_MUSHROOM
	const EVENT_SUNBURST_HIDDEN_PEARL
	const EVENT_SUNBURST_HIDDEN_SUN_STONE

; Crystal-exclusive events in Johto

; Kanto story events

; Kanto hidden items

; Kurt Apricorn events
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
	const EVENT_GAVE_KURT_BRN_APRICORN
; Phone events
	const EVENT_BUENA_OFFERED_HER_PHONE_NUMBER_NO_BLUE_CARD
; Ruins of Alph puzzles

; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_FAMICOM
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_VIRTUAL_BOY
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_DIGLETT_DOLL
	const EVENT_DECO_STARYU_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_SHELLDER_DOLL
	const EVENT_DECO_GRIMER_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_WEEDLE_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_MACHOP_DOLL
	const EVENT_DECO_TENTACOOL_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL
; Curio Shop Wares
	const EVENT_CURIO_SHOP_ROTOM_OVEN
	const EVENT_CURIO_SHOP_ROTOM_WASHER
	const EVENT_CURIO_SHOP_ROTOM_FRIDGE
	const EVENT_CURIO_SHOP_ROTOM_FAN
	const EVENT_CURIO_SHOP_ROTOM_MOWER
	const EVENT_CURIO_SHOP_SHELL
; More Johto story events

; More Crystal-exclusive events in Johto

; Trainer flags
; Swimmer F
	const EVENT_BEAT_SWIMMER_F_DAHLIA
	const EVENT_BEAT_SWIMMER_F_MAYA
	const EVENT_BEAT_SWIMMER_F_ZOEY
	const EVENT_BEAT_SWIMMER_F_ALLIE
	const EVENT_BEAT_SWIMMER_F_MORGAN
	const EVENT_BEAT_SWIMMER_F_LARA
	const EVENT_BEAT_SWIMMER_F_MINNIE
; Bird Keeper

; Boarder

; Sage

; Camper

; Burglar

; Biker

; Psychic

; Firebreather

; Fisher
	const EVENT_BEAT_FISHER_PIKE
	const EVENT_BEAT_FISHER_BOBBY
; Twins

; Schoolboy

; Picnicker

; Guitarist
	
; Juggler
	
; Gentleman

; Scientist
	const EVENT_BEAT_SCIENTIST_NAMBA_1
	
; Blackbelt

; Beauty
	const EVENT_BEAT_BEAUTY_ROSE
	const EVENT_BEAT_BEAUTY_YEVON
; Johto Gym Leaders

; Kanto Gym Leaders

; PokefanM

; PokefanF

; Kimono Girl

; Pokemaniac

; GruntM
	const EVENT_BEAT_AGENTM_1
	const EVENT_BEAT_BEEDRILL_GRUNT_1
	const EVENT_BEAT_AGENTM_2
	const EVENT_BEAT_HITMONCHAN_GRUNT_1
	const EVENT_BEAT_SPEAROW_GRUNT_1

; GruntF
	const EVENT_BEAT_AGENTF_1
	const EVENT_BEAT_AGENTF_2
	const EVENT_BEAT_AGENTF_3
	const EVENT_BEAT_AGENTF_4

; Lass
	const EVENT_BEAT_LASS_MARIBELLE
	const EVENT_BEAT_LASS_MILLIE
	const EVENT_BEAT_LASS_SANDY

; Hiker

; Bug Catcher
	const EVENT_BEAT_BUG_CATCHER_ASHTON
	const EVENT_BEAT_BUG_CATCHER_OWEN
	const EVENT_BEAT_BUG_CATCHER_ERIC
	const EVENT_BEAT_BUG_CATCHER_RYAN
; Officer

; CooltrainerM

; CooltrainerF

; ExecutiveF
	
; ExecutiveM

; Sailor

; Super Nerd

; Medium

; Skier

; SwimmerM
	const EVENT_BEAT_SWIMMER_M_CHAD
	const EVENT_BEAT_SWIMMER_M_LUKE
	const EVENT_BEAT_SWIMMER_M_BRAD
	const EVENT_BEAT_SWIMMER_M_LOGAN
; Youngster
	const EVENT_BEAT_YOUNGSTER_DONNY
	const EVENT_BEAT_YOUNGSTER_JAVI
	const EVENT_BEAT_YOUNGSTER_ALEX
	const EVENT_BEAT_YOUNGSTER_JEBADIAH
	const EVENT_BEAT_YOUNGSTER_JOSEPH
; Teacher

; Bug Catcher F
	const EVENT_BEAT_BUG_CATCHER_F_MICA
	const EVENT_BEAT_BUG_CATCHER_F_HANNAH
	
; Athlete
	const EVENT_BEAT_ATHLETE_TOMMY
	const EVENT_BEAT_ATHLETE_ZACK

; Elite Four and Champion

;Cross Battles
	const EVENT_CROSS_BATTLE_TANGELO_JUNGLE

;Tracey Battles
	const EVENT_TRACEY_BATTLE_TANGELO

; Crystal-exclusive trainer flags
	const EVENT_MOM_DEFEATED
	const EVENT_DRAKE_DEFEATED
	const EVENT_LUANA_DEFEATED
	const EVENT_RUDY_DEFEATED
	const EVENT_DANNY_DEFEATED
	const EVENT_CISSY_DEFEATED
	const EVENT_CRYSTAL_CAVE_BROCK_DEFEATED

; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
; Johto itemballs
	const EVENT_CHARMANDER_POKEBALL_IN_IVYS_LAB
	const EVENT_SQUIRTLE_POKEBALL_IN_IVYS_LAB
	const EVENT_BULBASAUR_POKEBALL_IN_IVYS_LAB
	const EVENT_ROUTE_49_POTION
	const EVENT_ROUTE_49_FRESHWATER
	const EVENT_OBTAINED_GS_BALL
	const EVENT_ALTERING_CAVE_SECRET_STASH
	const EVENT_ROUTE_49_NORTH_BEACH_GLASS
	const EVENT_ROUTE_49_NORTH_ETHER
	const EVENT_ROUTE_50_ANTIDOTE
	const EVENT_ROUTE_50_POKE_BALL
	const EVENT_ROUTE_51_REPEL
	const EVENT_ROUTE_51_POTION
	const EVENT_ROUTE_51_X_ATTACK
	const EVENT_TANGELO_JUNGLE_ANTIDOTE
	const EVENT_TANGELO_JUNGLE_POTION
	const EVENT_ROUTE_52_DIRE_HIT
	const EVENT_ROUTE_52_REPEL
	const EVENT_MIKAN_THICKET_CARBOS
	const EVENT_MIKAN_THICKET_ROSE_INCENSE
	const EVENT_MIKAN_ISLAND_WHITE_HERB
	const EVENT_MIKAN_ISLAND_TINY_BAMBOO
	const EVENT_MIKAN_RANCH_NUGGET
	const EVENT_ROUTE_53_GREAT_BALL
	const EVENT_ROUTE_53_SUPER_POTION
	const EVENT_MANDARIN_NORTH_RARE_CANDY
	const EVENT_RATICATE_RADIO_ESCAPE_ROPE
	const EVENT_RATICATE_RADIO_SMOKE_BALL
	const EVENT_SUNBURST_GREAT_BALL
	const EVENT_CRYSTAL_CAVE_GATE_SOOTHE_BELL
	const EVENT_ROUTE_55_SUPER_POTION
	const EVENT_ROUTE_55_SOFT_SAND
	const EVENT_ROUTE_55_PRETTY_SHELL
	const EVENT_ROUTE_55_ULTRA_BALL
; TMs (not necessarily all itemballs)
	const EVENT_TM_01_FOCUS_PUNCH
	const EVENT_TM_02_DRAGON_CLAW
	const EVENT_TM_03_WATER_PULSE
	const EVENT_TM_04_CALM_MIND
	const EVENT_TM_05_SIGNAL_BEAM
	const EVENT_TM_06_TOXIC
	const EVENT_TM_07_HAIL
	const EVENT_TM_08_BULK_UP
	const EVENT_TM_09_BULLET_SEED
    const EVENT_TM_10_WORK_UP
	const EVENT_TM_11_SUNNY_DAY
	const EVENT_TM_12_TAUNT
	const EVENT_TM_13_ICE_BEAM
	const EVENT_TM_14_BLIZZARD
	const EVENT_TM_15_HYPER_BEAM
	const EVENT_TM_16_LIGHT_SCREEN
	const EVENT_TM_17_PROTECT
	const EVENT_TM_18_RAIN_DANCE
	const EVENT_TM_19_GIGA_DRAIN
	const EVENT_TM_20_SAFEGAURD
    const EVENT_TM_21_DAZZLING_GLEAM
	const EVENT_TM_22_SOLARBEAM
	const EVENT_TM_23_IRON_TAIL
	const EVENT_TM_24_THUNDERBOLT
	const EVENT_TM_25_THUNDER
	const EVENT_TM_26_EARTHQUAKE
    const EVENT_TM_27_LOW_SWEEP
	const EVENT_TM_28_DIG
	const EVENT_TM_29_PSYCHIC
	const EVENT_TM_30_SHADOW_BALL
	const EVENT_TM_31_BRICK_BREAK
	const EVENT_TM_32_DOUBLE_TEAM
	const EVENT_TM_33_REFLECT
	const EVENT_TM_34_SHOCK_WAVE
	const EVENT_TM_35_FLAMETHROWER
	const EVENT_TM_36_SLUDGE_BOMB
	const EVENT_TM_37_SANDSTORM
	const EVENT_TM_38_FIRE_BLAST
	const EVENT_TM_39_ROCK_TOMB
	const EVENT_TM_40_AERIAL_ACE
	const EVENT_TM_41_TORMENT
	const EVENT_TM_42_FACADE
    const EVENT_TM_43_VOLT_SWITCH
	const EVENT_TM_44_REST
	const EVENT_TM_45_ATTRACT
	const EVENT_TM_46_THIEF
	const EVENT_TM_47_STEEL_WING
	const EVENT_TM_48_SKILL_SWAP
    const EVENT_TM_49_SCALD
	const EVENT_TM_50_OVERHEAT
	const EVENT_TM_51_ROOST
	const EVENT_TM_52_FOCUS_BLAST
	const EVENT_TM_53_ENERGY_BALL
	const EVENT_TM_54_FALSE_SWIPE
    const EVENT_TM_55_BRINE
	const EVENT_TM_56_FLING
	const EVENT_TM_57_CHARGE_BEAM
	const EVENT_TM_58_ENDURE
	const EVENT_TM_59_DRAGON_PULSE
	const EVENT_TM_60_DRAIN_PUNCH
	const EVENT_TM_61_WILL_O_WISP
    const EVENT_TM_62_BUG_BUZZ
    const EVENT_TM_63_NASTY_PLOT
	const EVENT_TM_64_EXPLOSION ; Replace this garbo
	const EVENT_TM_65_SHADOW_CLAW
	const EVENT_TM_66_PAYBACK
	const EVENT_TM_67_RECYCLE
	const EVENT_TM_68_GIGA_IMPACT
	const EVENT_TM_69_ROCK_POLISH
	const EVENT_TM_70_FLASH
	const EVENT_TM_71_STONE_EDGE
	const EVENT_TM_72_AVALANCHE
	const EVENT_TM_73_THUNDER_WAVE
	const EVENT_TM_74_GYRO_BALL
	const EVENT_TM_75_SWORDS_DANCE
	const EVENT_TM_76_STEALTH_ROCK
	const EVENT_TM_77_PSYCH_UP
    const EVENT_TM_78_SNARL
	const EVENT_TM_79_DARK_PULSE
	const EVENT_TM_80_ROCK_SLIDE
	const EVENT_TM_81_X_SCISSOR
	const EVENT_TM_82_SLEEP_TALK
    const EVENT_TM_83_BULLDOZE
	const EVENT_TM_84_POISON_JAB
	const EVENT_TM_85_DREAM_EATER
	const EVENT_TM_86_GRASS_KNOT
	const EVENT_TM_87_SWAGGER
	const EVENT_TM_88_PLUCK
	const EVENT_TM_89_U_TURN
	const EVENT_TM_90_SUBSTITUTE
	const EVENT_TM_91_FLASH_CANNON
	const EVENT_TM_92_TRICK_ROOM

; Johto people
	const EVENT_ROTOM_OVEN_PURCHASED
	const EVENT_ROTOM_WASH_PURCHASED
	const EVENT_ROTOM_FROST_PURCHASED
	const EVENT_ROTOM_FAN_PURCHASED
	const EVENT_ROTOM_MOW_PURCHASED
	const EVENT_DRATINI_VALENCIA_APPEAR
	const EVENT_ALT_STARTER_VALENCIA_IVY
	const EVENT_MARILL_TANGELO_1
	const EVENT_MARILL_TANGELO_2
	const EVENT_MARILL_TANGELO_3
	const EVENT_TANGELO_ROCKETS_DEFEATED
	const EVENT_GS_BALL_ENCOUNTER
	const EVENT_LAPRAS_OBTAINED
	const EVENT_TRACEY_TANGELO_CENTER_INSIDE
	const EVENT_GS_BALL_IVY
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const EVENT_SENTA_AT_HOME
	const EVENT_MANDARIN_NORTH_CLEARED_RADIO_TOWER
	const EVENT_MANDARIN_NORTH_OLD_LADY_HELPED
	const EVENT_MANDARIN_NORTH_ZORUA_ILLUSIONED
	const EVENT_MANDARIN_NORTH_CROSS_LEAVING_CUT_MASTER
	const EVENT_RATICATE_RADIO_B1F_BUTCH
	const EVENT_RATICATE_RADIO_B1F_CASSIDY
	const EVENT_RATICATE_RADIO_B1F_LOOKER
	const EVENT_RATICATE_RADIO_LOBBY_LOOKER
	const EVENT_RATICATE_RADIO_B2F_YELLOW
	const EVENT_RATICATE_RADIO_B2F_DROWZEE
	const EVENT_MATEOS_PASSION_RESTORED
	const EVENT_MATEO_SIDEQUEST_STARTED
	const EVENT_MATEO_LEFT_SHOP
	const EVENT_BROCK_LEFT_SHOP
	const EVENT_REMOVE_SUNBURST_CUT_TREES
	const EVENT_CRYSTAL_CAVE_1F_SCENE
	const EVENT_CRYSTAL_CAVE_B1F_SCENE
	const EVENT_CRYSTAL_CAVE_B1F_SCENE2
	const EVENT_CRYSTAL_ONIX_ENCOUNTER
; Kanto people

; Kanto itemballs
	
; New to Crystal

; Dummy Event To Silence Errors
	const EVENT_DUMMY_OUT
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
	const EVENT_INITIALIZED_EVENTS
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
        const EVENT_PLAYERS_HOUSE_2F_DOLL_2
        const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
        const EVENT_PLAYERS_HOUSE_TMHM_GIVER
        const EVENT_LISTENED_TO_INITIAL_RADIO
        const EVENT_WELCOMED_TO_POKECOM_CENTER
	
; Magikarp House flags
	const EVENT_LAKE_OF_RAGE_ELIXIR_ON_STANDBY
	const EVENT_LAKE_OF_RAGE_ASKED_FOR_MAGIKARP
	
; Berry Master's House
	const EVENT_BERRY_MASTER_GD_HAS_BLOCK
	const EVENT_BERRY_MASTER_GD_FIRST_TIME
	const EVENT_BERRY_MASTER_GD_HOLDING_GRASSY_BLOCK
	const EVENT_BERRY_MASTER_GD_HOLDING_FIERY_BLOCK
	const EVENT_BERRY_MASTER_GD_HOLDING_CHILLY_BLOCK
	const EVENT_BERRY_MASTER_GD_HOLDING_ZAPPY_BLOCK
	const EVENT_BERRY_MASTER_GD_HOLDING_LOVELY_BLOCK
	const EVENT_BERRY_MASTER_GD_HOLDING_CRUNCHYBLOCK
	
; PokeBlock Swarm Flags
	const EVENT_BLOCK_ON_PINKAN_ISLAND
	const EVENT_BLOCK_IN_ALTERING_CAVE
	const EVENT_BLOCK_ON_METALLICA_ISLAND
	const EVENT_BLOCK_ON_CAMOMILE_ISLAND
	const EVENT_BLOCK_ON_TARROCO_ISLAND

DEF NUM_EVENTS EQU const_value
