; sprite ids
; OverworldSprites indexes (see data/sprites/sprites.asm)
	const_def
	const SPRITE_NONE ; 00
	const SPRITE_CHRIS ; 01
	const SPRITE_CHRIS_BIKE ; 02
	const SPRITE_GAMEBOY_KID ; 03
	const SPRITE_RIVAL ; 04
	const SPRITE_OAK ; 05
	const SPRITE_RED ; 06
	const SPRITE_BLUE ; 07
	const SPRITE_BILL ; 08
	const SPRITE_ELDER ; 09
	const SPRITE_JANINE ; 0a
	const SPRITE_KURT ; 0b
	const SPRITE_MOM ; 0c
	const SPRITE_BLAINE ; 0d
	const SPRITE_REDS_MOM ; 0e
	const SPRITE_DAISY ; 0f
	const SPRITE_ELM ; 10
	const SPRITE_WILL ; 11
	const SPRITE_LOOKER ; 12
	const SPRITE_MATEO ; 13
	const SPRITE_BUGSY ; 14
	const SPRITE_MORTY ; 15
	const SPRITE_CHUCK ; 16
	const SPRITE_JASMINE ; 17
	const SPRITE_PRYCE ; 18
	const SPRITE_CLAIR ; 19
	const SPRITE_BROCK ; 1a
	const SPRITE_KAREN ; 1b
	const SPRITE_BRUNO ; 1c
	const SPRITE_MISTY ; 1d
	const SPRITE_LANCE ; 1e
	const SPRITE_SURGE ; 1f
	const SPRITE_ERIKA ; 20
	const SPRITE_KOGA ; 21
	const SPRITE_SABRINA ; 22
	const SPRITE_COOLTRAINER_M ; 23
	const SPRITE_COOLTRAINER_F ; 24
	const SPRITE_BUG_CATCHER ; 25
	const SPRITE_TWIN ; 26
	const SPRITE_YOUNGSTER ; 27
	const SPRITE_LASS ; 28
	const SPRITE_TEACHER ; 29
	const SPRITE_BEAUTY ; 2a
	const SPRITE_SUPER_NERD ; 2b
	const SPRITE_ROCKER ; 2c
	const SPRITE_POKEFAN_M ; 2d
	const SPRITE_POKEFAN_F ; 2e
	const SPRITE_GRAMPS ; 2f
	const SPRITE_GRANNY ; 30
	const SPRITE_SWIMMER_GUY ; 31
	const SPRITE_SWIMMER_GIRL ; 32
	const SPRITE_BIG_SNORLAX ; 33
	const SPRITE_SURFING_PIKACHU ; 34
	const SPRITE_ROCKET ; 35
	const SPRITE_ROCKET_GIRL ; 36
	const SPRITE_NURSE ; 37
	const SPRITE_LINK_RECEPTIONIST ; 38
	const SPRITE_CLERK ; 39
	const SPRITE_FISHER ; 3a
	const SPRITE_FISHING_GURU ; 3b
	const SPRITE_SCIENTIST ; 3c
	const SPRITE_KIMONO_GIRL ; 3d
	const SPRITE_SAGE ; 3e
	const SPRITE_GENTLEMAN ; 40
	const SPRITE_BLACK_BELT ; 41
	const SPRITE_RECEPTIONIST ; 42
	const SPRITE_OFFICER ; 43
	const SPRITE_CAL ; 44
	const SPRITE_SLOWPOKE ; 45
	const SPRITE_CAPTAIN ; 46
	const SPRITE_BIG_LAPRAS ; 47
	const SPRITE_GYM_GUIDE ; 48
	const SPRITE_SAILOR ; 49
	const SPRITE_BIKER ; 4a
	const SPRITE_PHARMACIST ; 4b
	const SPRITE_MONSTER ; 4c
	const SPRITE_FAIRY ; 4d
	const SPRITE_BIRD ; 4e
	const SPRITE_DRAGON ; 4f
	const SPRITE_BIG_ONIX ; 50
	const SPRITE_N64 ; 51
	const SPRITE_SUDOWOODO ; 52
	const SPRITE_SURF ; 53
	const SPRITE_POKE_BALL ; 54
	const SPRITE_POKEDEX ; 55
	const SPRITE_PAPER ; 56
	const SPRITE_VIRTUAL_BOY ; 57
	const SPRITE_PC_GIRL ; 58
	const SPRITE_ROCK ; 59
	const SPRITE_BOULDER ; 5a
	const SPRITE_SNES ; 5b
	const SPRITE_FAMICOM ; 5c
	const SPRITE_FRUIT_TREE ; 5d
	const SPRITE_GOLD_TROPHY ; 5e
	const SPRITE_SILVER_TROPHY ; 5f
	const SPRITE_KRIS ; 60
	const SPRITE_KRIS_BIKE ; 61
	const SPRITE_SUICUNE ; 62
	const SPRITE_ENTEI ; 63
	const SPRITE_RAIKOU ; 64
	const SPRITE_WALKING_SWIMMER_GIRL ; 65
	const SPRITE_LORELEI ; 66
	const SPRITE_GS_BALL ; 67
	const SPRITE_AIDE ; 68
	const SPRITE_ROCKET_BALL ; 69
	const SPRITE_SHADOW ; 6a
	const SPRITE_TRACEY ; 6b
	const SPRITE_MARILL_WALK ; 6c
	const SPRITE_OFFICER_F ;6d
	const SPRITE_OFFICER_F_BORED ; 6e
	const SPRITE_PC_GUY ; 6f
	const SPRITE_CISSY ; 70
	const SPRITE_SIGHTSEER ; 71
	const SPRITE_BUG_MANIAC ; 72
	const SPRITE_SHELL ; 73
	const SPRITE_MAYOR ; 74
	const SPRITE_TANGELO_JUNGLE_SCENE ; 75
	const SPRITE_WALKING_SWIMMER_GUY ; 76
	const SPRITE_SENTA ; 77
	const SPRITE_ROTOM_OVEN ; 77
	const SPRITE_ROTOM_WASHER ; 77
	const SPRITE_ROTOM_FRIDGE ; 77
	const SPRITE_ROTOM_FAN ; 77
	const SPRITE_ROTOM_MOWER ; 77
	const SPRITE_CHRIS_DIVE ; 77
	const SPRITE_KRIS_DIVE ; 77
	
; sprites_berries not split yet
	const SPRITE_BERRY_A_2 ; CHERI/BLUE
	const SPRITE_BERRY_B_1 ; CHESTO/TEAL
	const SPRITE_BERRY_B_2 ; HOPO/GREEN, LIGARC/PURPLE
	const SPRITE_BERRY_C_2 ; PECHA/PINK
	const SPRITE_BERRY_D_2 ; RAWST/RED COBA/YELLOW
	const SPRITE_BERRY_E_2 ; ASPEAR/RED
	const SPRITE_BERRY_F_2 ; LEPPA/RED, TOTAPO/BROWN
	const SPRITE_BERRY_G_2 ; ORAN/AZURE
	const SPRITE_BERRY_H_1 ; DRASH/RED, PERSIM/BLUE, SHUCA/PINK, HABAN/YELLOW
	const SPRITE_BERRY_I_2 ; EGGANT/AZURE, LUM/GREEN
	const SPRITE_BERRY_J_2 ; SITRUS/GRAY, WEPEAR/BROWN, QUALOT/GREEN, COLBUR/BLUE, MICLE/RED, ROSELI/PINK
	const SPRITE_BERRY_K_2 ; PUMKIN/ORANGE, RABUTA/AZURE, WATMEL/BROWN
	const SPRITE_BERRY_L_1 ; STRIB/GREEN
	const SPRITE_BERRY_L_2 ; RINDO/PURPLE, TOMATO/BLUE, 
	const SPRITE_BERRY_M_1 ; TILOTA/GREEN, OCCA/CYAN 
	const SPRITE_BERRY_M_2 ; PAMTRE/BLUE
	const SPRITE_BERRY_N_1 ; GANLON/AZURE, HONDEW/GREEN
	const SPRITE_BERRY_N_2 ; NUTPEA/BROWN, BELUE/BLUE, KASIB/GREEN
	const SPRITE_BERRY_O_2 ; UNYINN/PINK, GREPA/RED, KEBIA/TEAL, CHILAN/GREEN, APICOT/YELLOW
	const SPRITE_BERRY_P_2 ; KRAO/PURPLE, PAYAPA/BLUE, NOMEL/GREEN, PINKAN/PINK
	const SPRITE_BERRY_Q_2 ; BITMEL/GREEN, MAGO/GREEN, NANAB/PURPLE, CHOPLE/YELLOW
	const SPRITE_BERRY_R_1 ; BLUK/AZURE
	const SPRITE_BERRY_R_2 ; CAREEP/GRAY, RAZZ/PURPLE, WACAN/GREEN
	const SPRITE_BERRY_S_2 ; FIGY/PURPLE
	const SPRITE_BERRY_T_2 ; WIKI/BLUE
	const SPRITE_BERRY_U_2 ; AGUAV/GREEN, SALAC/YELLOW
	const SPRITE_BERRY_V_1 ; IAPAPA/YELLOW, PINAP/GREEN
	const SPRITE_BERRY_W_2 ; POMEG/RED
	const SPRITE_BERRY_X_2 ; KELPSY/BLUE
	const SPRITE_BERRY_Y_1 ; STARF/GREEN
	const SPRITE_BERRY_Y_2 ; CORNN/BLUE, JABOCA/YELLOW, TANGA/GREEN
	const SPRITE_BERRY_Z_1 ; MAGOST/YELLOW, PETAYA/AZURE
	const SPRITE_BERRY_ALPHA_2 ; SPELON/AZURE
	const SPRITE_BERRY_BETA_2 ; DURIN/GRAY, ENIGA/BROWN
	const SPRITE_BERRY_GAMMA_1 ; PASSHO/TEAL, ROWAP/BLUE
	const SPRITE_BERRY_DELTA_1 ; YACHE/TEAL
	const SPRITE_BERRY_EPSILON_2 ; CHARTI/GREEN, LANSAT/AZURE
	const SPRITE_BERRY_ZETA_1 ; BABIRI/AZURE, KEE/ORANGE
	const SPRITE_BERRY_ZETA_2 ; LIECHI/GREEN, CUSTAP/BLUE
	const SPRITE_BERRY_ETA_1 ; MARANGA/BLUE
DEF NUM_OVERWORLD_SPRITES EQU const_value - 1

; SpriteMons indexes (see data/sprites/sprite_mons.asm)
DEF SPRITE_POKEMON EQU const_value
	const SPRITE_UNOWN ; 80
	const SPRITE_GEODUDE ; 81
	const SPRITE_GROWLITHE ; 82
	const SPRITE_WEEDLE ; 83
	const SPRITE_SHELLDER ; 84
	const SPRITE_ODDISH ; 85
	const SPRITE_GENGAR ; 86
	const SPRITE_MAGIKARP ; 88
	const SPRITE_SQUIRTLE ; 89
	const SPRITE_TOGEPI ; 8a
	const SPRITE_BUTTERFREE ; 8b
	const SPRITE_DIGLETT ; 8c
	const SPRITE_POLIWAG ; 8d
	const SPRITE_PIKACHU ; 8e
	const SPRITE_CLEFAIRY ; 8f
	const SPRITE_CHARMANDER ; 90
	const SPRITE_DROWZEE ; 91
	const SPRITE_STARMIE ; 92
	const SPRITE_BULBASAUR ; 93
	const SPRITE_JIGGLYPUFF ; 94
	const SPRITE_GRIMER ; 95
	const SPRITE_EKANS ; 96
	const SPRITE_PARAS ; 97
	const SPRITE_TENTACOOL ; 98
	const SPRITE_MILTANK ; 99
	const SPRITE_TAUROS ; 99
	const SPRITE_MACHOP ; 9a
	const SPRITE_VOLTORB ; 9b
	const SPRITE_LAPRAS ; 9c
	const SPRITE_RHYDON ; 9d
	const SPRITE_MOLTRES ; 9e
	const SPRITE_SNORLAX ; 9f
	const SPRITE_GYARADOS ; a0
	const SPRITE_LUGIA ; a1
	const SPRITE_HO_OH ; a2
	const SPRITE_DRATINI ; a3
	const SPRITE_CHIKORITA ; a4
	const SPRITE_CYNDAQUIL ; a5
	const SPRITE_TOTODILE ; a6
DEF NUM_POKEMON_SPRITES EQU const_value - SPRITE_POKEMON

; special GetMonSprite values (see engine/overworld/overworld.asm)
	const SPRITE_DAY_CARE_MON_1 ; e0
	const SPRITE_DAY_CARE_MON_2 ; e1

; wVariableSprites indexes (see wram.asm)
	const_next $f0
DEF SPRITE_VARS EQU const_value
	const SPRITE_CONSOLE ; f0
	const SPRITE_DOLL_1 ; f1
	const SPRITE_DOLL_2 ; f2
	const SPRITE_BIG_DOLL ; f3
	const SPRITE_WEIRD_TREE ; f4
	const SPRITE_FUCHSIA_GYM_1 ; f7
	const SPRITE_FUCHSIA_GYM_2 ; f8
	const SPRITE_FUCHSIA_GYM_3 ; f9
	const SPRITE_FUCHSIA_GYM_4 ; fa
	const SPRITE_COPYCAT ; fb
	const SPRITE_JANINE_IMPERSONATOR ; fc
	const SPRITE_LINK_TRAINER ; fd
	const SPRITE_BATTLE_TOWER_OPPONENT ; fe
