NightMusicTable:
MACRO night_music
	db \1, \2
ENDM

	night_music MUSIC_EARLY_ORANGE_ROUTE,    MUSIC_EARLY_ORANGE_ROUTE_NIGHT
	night_music MUSIC_CITY_ORANGE,    MUSIC_CITY_ORANGE_NIGHT
	night_music MUSIC_SQUISHY,    MUSIC_SQUISHY_NIGHT
	night_music MUSIC_STARTER_ORANGE_ROUTE,    MUSIC_STARTER_ORANGE_ROUTE_NIGHT
	night_music MUSIC_SOME_ROUTE_ORANGE,    MUSIC_SOME_ROUTE_ORANGE_NIGHT
	night_music MUSIC_SLATEPORT_CITY,    MUSIC_SLATEPORT_CITY_NIGHT
	night_music MUSIC_PINKAN_ISLAND,    MUSIC_PINKAN_ISLAND_NIGHT
	db -1 ; end