Cries:
; entries correspond to CRY_* constants (see constants/cry_constants.asm)
	table_width 3
	dba Cry_Nidoran_M
	dba Cry_Nidoran_F
	dba Cry_Slowpoke
	dba Cry_Kangaskhan
	dba Cry_Charmander
	dba Cry_Grimer
	dba Cry_Voltorb
	dba Cry_Muk
	dba Cry_Oddish
	dba Cry_Raichu
	dba Cry_Nidoqueen
	dba Cry_Diglett
	dba Cry_Seel
	dba Cry_Drowzee
	dba Cry_Pidgey
	dba Cry_Bulbasaur
	dba Cry_Spearow
	dba Cry_Rhydon
	dba Cry_Golem
	dba Cry_Blastoise
	dba Cry_Pidgeotto
	dba Cry_Weedle
	dba Cry_Caterpie
	dba Cry_Ekans
	dba Cry_Fearow
	dba Cry_Clefairy
	dba Cry_Venonat
	dba Cry_Lapras
	dba Cry_Metapod
	dba Cry_Squirtle
	dba Cry_Paras
	dba Cry_Growlithe
	dba Cry_Krabby
	dba Cry_Psyduck
	dba Cry_Rattata
	dba Cry_Vileplume
	dba Cry_Vulpix
	dba Cry_Weepinbell
	dba Cry_Marill
	dba Cry_Spinarak
	dba Cry_Togepi
	dba Cry_Girafarig
	dba Cry_Raikou
	dba Cry_Mareep
	dba Cry_Togetic
	dba Cry_Hoothoot
	dba Cry_Sentret
	dba Cry_Slowking
	dba Cry_Cyndaquil
	dba Cry_Chikorita
	dba Cry_Totodile
	dba Cry_Gligar
	dba Cry_Cleffa
	dba Cry_Slugma
	dba Cry_Ledyba
	dba Cry_Entei
	dba Cry_Wooper
	dba Cry_Mantine
	dba Cry_Typhlosion
	dba Cry_Natu
	dba Cry_Teddiursa
	dba Cry_Sunflora
	dba Cry_Ampharos
	dba Cry_Magcargo
        dba Cry_Pichu
        dba Cry_Aipom
        dba Cry_Dunsparce
        dba Cry_Donphan
        dba Cry_Poochyena
	dba Cry_Mightyena
        dba Cry_Zigzagoon
        dba Cry_Wingull
	dba Cry_Pelipper
        dba Cry_Ralts
        dba Cry_Kirlia
        dba Cry_Gallade
        dba Cry_Shroomish
	dba Cry_Breloom
        dba Cry_Nincada
        dba Cry_Azurill
        dba Cry_Latias
        dba Cry_Aron
	dba Cry_Lairon
	dba Cry_Aggron
        dba Cry_Carvanha
        dba Cry_Wailmer
        dba Cry_Numel
        dba Cry_Spoink
        dba Cry_Spinda
        dba Cry_Trapinch
        dba Cry_Swablu
        dba Cry_Zangoose
        dba Cry_Seviper
        dba Cry_Feebas
	dba Cry_Milotic
        dba Cry_Kecleon
        dba Cry_Shuppet
        dba Cry_Duskull
        dba Cry_Tropius
        dba Cry_Chimecho
        dba Cry_Wynaut
        dba Cry_Snorunt
        dba Cry_Spheal
        dba Cry_Relicanth
        dba Cry_Luvdisc
        dba Cry_Shinx
        dba Cry_Cherubi
        dba Cry_Chatot
        dba Cry_Riolu
        dba Cry_Croagunk
        dba Cry_Carnivine
        dba Cry_Finneon
        dba Cry_Rotom
        dba Cry_Phione
        dba Cry_Ferroseed
        dba Cry_Stunfisk
        dba Cry_Pawniard
        dba Cry_Zorua
        dba Cry_Skrelp
        dba Cry_Clauncher
        dba Cry_Sylveon
        dba Cry_Pancham
        dba Cry_Inkay
        dba Cry_Noibat
        dba Cry_Honedge
        dba Cry_Goomy
        dba Cry_Rockruff
        dba Cry_Cutiefly
        dba Cry_Pikipek
        dba Cry_Mimikyu
        dba Cry_Sandygast
        dba Cry_Salandit
        dba Cry_Mareanie
        dba Cry_Turtonator
        dba Cry_Dhelmise
        dba Cry_Pincurchin
        dba Cry_Cramorant
        dba Cry_Binacle
        dba Cry_Applin
        dba Cry_Gimmighoul
        dba Cry_Annihilape
        dba Cry_Dudunsparce
        dba Cry_Farigiraf
        dba Cry_Kingambit
        dba Cry_Dipplin
        dba Cry_Charcadet
        dba Cry_Clodsire
        dba Cry_Cursola
        dba Cry_Perrserker
        dba Cry_Sirfetchd
        dba Cry_MrRime
        dba Cry_Obstagoon
        dba Cry_Overqwil
        dba Cry_Sneasler
        dba Cry_Kleavor
        dba Cry_Ursaluna
        dba Cry_Wyrdeer
        dba Cry_Marshadow
        dba Cry_Meltan
        dba Cry_Melmetal
        assert_table_length NUM_CRIES
