SECTION "Give All TMs/HMs Script", ROMX
EXPORT GiveAllTMsHMsScript

GiveAllTMsHMsScript:
        giveitem TM_FOCUS_PUNCH
        giveitem TM_DRAGON_CLAW
        giveitem TM_WATER_PULSE
        giveitem TM_CALM_MIND
        giveitem TM_ROAR
        giveitem TM_TOXIC
        giveitem TM_HAIL
        giveitem TM_BULK_UP
        giveitem TM_BULLET_SEED
        giveitem TM_WORK_UP
        giveitem TM_SUNNY_DAY
        giveitem TM_TAUNT
        giveitem TM_ICE_BEAM
        giveitem TM_BLIZZARD
        giveitem TM_HYPER_BEAM
        giveitem TM_LIGHT_SCREEN
        giveitem TM_PROTECT
        giveitem TM_RAIN_DANCE
        giveitem TM_GIGA_DRAIN
        giveitem TM_SAFEGUARD
        giveitem TM_DAZZLING_GLEAM
        giveitem TM_SOLARBEAM
        giveitem TM_IRON_TAIL
        giveitem TM_THUNDERBOLT
        giveitem TM_THUNDER
        giveitem TM_EARTHQUAKE
        giveitem TM_LOW_SWEEP
        giveitem TM_DIG
        giveitem TM_PSYCHIC_M
        giveitem TM_SHADOW_BALL
        giveitem TM_BRICK_BREAK
        giveitem TM_DOUBLE_TEAM
        giveitem TM_REFLECT
        giveitem TM_SHOCK_WAVE
        giveitem TM_FLAMETHROWER
        giveitem TM_SLUDGE_BOMB
        giveitem TM_SANDSTORM
        giveitem TM_FIRE_BLAST
        giveitem TM_ROCK_TOMB
        giveitem TM_AERIAL_ACE
        giveitem TM_TORMENT
        giveitem TM_FACADE
        giveitem TM_VOLT_SWITCH
        giveitem TM_REST
        giveitem TM_ATTRACT
        giveitem TM_THIEF
        giveitem TM_STEEL_WING
        giveitem TM_SKILL_SWAP
        giveitem TM_SCALD
        giveitem TM_OVERHEAT
        giveitem TM_ROOST
        giveitem TM_FOCUS_BLAST
        giveitem TM_ENERGY_BALL
        giveitem TM_FALSE_SWIPE
        giveitem TM_BRINE
        giveitem TM_FLING
        giveitem TM_CHARGE_BEAM
        giveitem TM_ENDURE
        giveitem TM_DRAGON_PULSE
        giveitem TM_DRAIN_PUNCH
        giveitem TM_WILL_O_WISP
        giveitem TM_BUG_BUZZ
        giveitem TM_NASTY_PLOT
        giveitem TM_EXPLOSION
        giveitem TM_SHADOW_CLAW
        giveitem TM_PAYBACK
        giveitem TM_RECYCLE
        giveitem TM_GIGA_IMPACT
        giveitem TM_ROCK_POLISH
        giveitem TM_FLASH
        giveitem TM_STONE_EDGE
        giveitem TM_AVALANCHE
        giveitem TM_THUNDER_WAVE
        giveitem TM_GYRO_BALL
        giveitem TM_SWORDS_DANCE
        giveitem TM_STEALTH_ROCK
        giveitem TM_PSYCH_UP
        giveitem TM_SNARL
        giveitem TM_DARK_PULSE
        giveitem TM_ROCK_SLIDE
        giveitem TM_X_SCISSOR
        giveitem TM_SLEEP_TALK
        giveitem TM_BULLDOZE
        giveitem TM_POISON_JAB
        giveitem TM_DREAM_EATER
        giveitem TM_GRASS_KNOT
        giveitem TM_SWAGGER
        giveitem TM_PLUCK
        giveitem TM_U_TURN
        giveitem TM_SUBSTITUTE
        giveitem TM_FLASH_CANNON
       giveitem TM_TRICK_ROOM
       giveitem HM_CUT
       giveitem HM_FLY
       giveitem HM_SURF
       giveitem HM_STRENGTH
       giveitem HM_WHIRLPOOL
       giveitem HM_ROCK_SMASH
       giveitem HM_WATERFALL
       giveitem HM_DIVE
       giveitem HM_ROCK_CLIMB
       end
