Footprints:
	table_width TILE_1BPP_SIZE * 4

; Kanto
INCBIN "gfx/footprints/kanto/bulbasaur.1bpp"
INCBIN "gfx/footprints/kanto/ivysaur.1bpp"
INCBIN "gfx/footprints/kanto/venusaur.1bpp"
INCBIN "gfx/footprints/kanto/charmander.1bpp"
INCBIN "gfx/footprints/kanto/charmeleon.1bpp"
INCBIN "gfx/footprints/kanto/charizard.1bpp"
INCBIN "gfx/footprints/kanto/squirtle.1bpp"
INCBIN "gfx/footprints/kanto/wartortle.1bpp"
INCBIN "gfx/footprints/kanto/blastoise.1bpp"
INCBIN "gfx/footprints/kanto/caterpie.1bpp"
INCBIN "gfx/footprints/kanto/metapod.1bpp"
INCBIN "gfx/footprints/kanto/butterfree.1bpp"
INCBIN "gfx/footprints/kanto/weedle.1bpp"
INCBIN "gfx/footprints/kanto/kakuna.1bpp"
INCBIN "gfx/footprints/kanto/beedrill.1bpp"
INCBIN "gfx/footprints/kanto/pidgey.1bpp"
INCBIN "gfx/footprints/kanto/pidgeotto.1bpp"
INCBIN "gfx/footprints/kanto/pidgeot.1bpp"
INCBIN "gfx/footprints/kanto/rattata.1bpp"
INCBIN "gfx/footprints/kanto/raticate.1bpp"
INCBIN "gfx/footprints/kanto/spearow.1bpp"
INCBIN "gfx/footprints/kanto/fearow.1bpp"
INCBIN "gfx/footprints/kanto/ekans.1bpp"
INCBIN "gfx/footprints/kanto/arbok.1bpp"
INCBIN "gfx/footprints/kanto/pikachu.1bpp"
INCBIN "gfx/footprints/kanto/raichu.1bpp"
INCBIN "gfx/footprints/kanto/sandshrew.1bpp"
INCBIN "gfx/footprints/kanto/sandslash.1bpp"
INCBIN "gfx/footprints/kanto/nidoran_f.1bpp"
INCBIN "gfx/footprints/kanto/nidorina.1bpp"
INCBIN "gfx/footprints/kanto/nidoqueen.1bpp"
INCBIN "gfx/footprints/kanto/nidoran_m.1bpp"
INCBIN "gfx/footprints/kanto/nidorino.1bpp"
INCBIN "gfx/footprints/kanto/nidoking.1bpp"
INCBIN "gfx/footprints/kanto/clefairy.1bpp"
INCBIN "gfx/footprints/kanto/clefable.1bpp"
INCBIN "gfx/footprints/kanto/vulpix.1bpp"
INCBIN "gfx/footprints/kanto/ninetales.1bpp"
INCBIN "gfx/footprints/kanto/jigglypuff.1bpp"
INCBIN "gfx/footprints/kanto/wigglytuff.1bpp"
INCBIN "gfx/footprints/kanto/zubat.1bpp"
INCBIN "gfx/footprints/kanto/golbat.1bpp"
INCBIN "gfx/footprints/kanto/oddish.1bpp"
INCBIN "gfx/footprints/kanto/gloom.1bpp"
INCBIN "gfx/footprints/kanto/vileplume.1bpp"
INCBIN "gfx/footprints/kanto/paras.1bpp"
INCBIN "gfx/footprints/kanto/parasect.1bpp"
INCBIN "gfx/footprints/kanto/venonat.1bpp"
INCBIN "gfx/footprints/kanto/venomoth.1bpp"
INCBIN "gfx/footprints/kanto/diglett.1bpp"
INCBIN "gfx/footprints/kanto/dugtrio.1bpp"
INCBIN "gfx/footprints/kanto/meowth.1bpp"
INCBIN "gfx/footprints/kanto/persian.1bpp"
INCBIN "gfx/footprints/kanto/psyduck.1bpp"
INCBIN "gfx/footprints/kanto/golduck.1bpp"
INCBIN "gfx/footprints/kanto/mankey.1bpp"
INCBIN "gfx/footprints/kanto/primeape.1bpp"
INCBIN "gfx/footprints/kanto/growlithe.1bpp"
INCBIN "gfx/footprints/kanto/arcanine.1bpp"
INCBIN "gfx/footprints/kanto/poliwag.1bpp"
INCBIN "gfx/footprints/kanto/poliwhirl.1bpp"
INCBIN "gfx/footprints/kanto/poliwrath.1bpp"
INCBIN "gfx/footprints/kanto/abra.1bpp"
INCBIN "gfx/footprints/kanto/kadabra.1bpp"
INCBIN "gfx/footprints/kanto/alakazam.1bpp"
INCBIN "gfx/footprints/kanto/machop.1bpp"
INCBIN "gfx/footprints/kanto/machoke.1bpp"
INCBIN "gfx/footprints/kanto/machamp.1bpp"
INCBIN "gfx/footprints/kanto/bellsprout.1bpp"
INCBIN "gfx/footprints/kanto/weepinbell.1bpp"
INCBIN "gfx/footprints/kanto/victreebel.1bpp"
INCBIN "gfx/footprints/kanto/tentacool.1bpp"
INCBIN "gfx/footprints/kanto/tentacruel.1bpp"
INCBIN "gfx/footprints/kanto/geodude.1bpp"
INCBIN "gfx/footprints/kanto/graveler.1bpp"
INCBIN "gfx/footprints/kanto/golem.1bpp"
INCBIN "gfx/footprints/kanto/ponyta.1bpp"
INCBIN "gfx/footprints/kanto/rapidash.1bpp"
INCBIN "gfx/footprints/kanto/slowpoke.1bpp"
INCBIN "gfx/footprints/kanto/slowbro.1bpp"
INCBIN "gfx/footprints/kanto/magnemite.1bpp"
INCBIN "gfx/footprints/kanto/magneton.1bpp"
INCBIN "gfx/footprints/kanto/farfetch_d.1bpp"
INCBIN "gfx/footprints/kanto/doduo.1bpp"
INCBIN "gfx/footprints/kanto/dodrio.1bpp"
INCBIN "gfx/footprints/kanto/seel.1bpp"
INCBIN "gfx/footprints/kanto/dewgong.1bpp"
INCBIN "gfx/footprints/kanto/grimer.1bpp"
INCBIN "gfx/footprints/kanto/muk.1bpp"
INCBIN "gfx/footprints/kanto/shellder.1bpp"
INCBIN "gfx/footprints/kanto/cloyster.1bpp"
INCBIN "gfx/footprints/kanto/gastly.1bpp"
INCBIN "gfx/footprints/kanto/haunter.1bpp"
INCBIN "gfx/footprints/kanto/gengar.1bpp"
INCBIN "gfx/footprints/kanto/onix.1bpp"
INCBIN "gfx/footprints/kanto/drowzee.1bpp"
INCBIN "gfx/footprints/kanto/hypno.1bpp"
INCBIN "gfx/footprints/kanto/krabby.1bpp"
INCBIN "gfx/footprints/kanto/kingler.1bpp"
INCBIN "gfx/footprints/kanto/voltorb.1bpp"
INCBIN "gfx/footprints/kanto/electrode.1bpp"
INCBIN "gfx/footprints/kanto/exeggcute.1bpp"
INCBIN "gfx/footprints/kanto/exeggutor.1bpp"
INCBIN "gfx/footprints/kanto/cubone.1bpp"
INCBIN "gfx/footprints/kanto/marowak.1bpp"
INCBIN "gfx/footprints/kanto/hitmonlee.1bpp"
INCBIN "gfx/footprints/kanto/hitmonchan.1bpp"
INCBIN "gfx/footprints/kanto/lickitung.1bpp"
INCBIN "gfx/footprints/kanto/koffing.1bpp"
INCBIN "gfx/footprints/kanto/weezing.1bpp"
INCBIN "gfx/footprints/kanto/rhyhorn.1bpp"
INCBIN "gfx/footprints/kanto/rhydon.1bpp"
INCBIN "gfx/footprints/kanto/chansey.1bpp"
INCBIN "gfx/footprints/kanto/tangela.1bpp"
INCBIN "gfx/footprints/kanto/kangaskhan.1bpp"
INCBIN "gfx/footprints/kanto/horsea.1bpp"
INCBIN "gfx/footprints/kanto/seadra.1bpp"
INCBIN "gfx/footprints/kanto/goldeen.1bpp"
INCBIN "gfx/footprints/kanto/seaking.1bpp"
INCBIN "gfx/footprints/kanto/staryu.1bpp"
INCBIN "gfx/footprints/kanto/starmie.1bpp"
INCBIN "gfx/footprints/kanto/mr__mime.1bpp"
INCBIN "gfx/footprints/kanto/scyther.1bpp"
INCBIN "gfx/footprints/kanto/jynx.1bpp"
INCBIN "gfx/footprints/kanto/electabuzz.1bpp"
INCBIN "gfx/footprints/kanto/magmar.1bpp"
INCBIN "gfx/footprints/kanto/pinsir.1bpp"
INCBIN "gfx/footprints/kanto/tauros.1bpp"
INCBIN "gfx/footprints/kanto/magikarp.1bpp"
INCBIN "gfx/footprints/kanto/gyarados.1bpp"
INCBIN "gfx/footprints/kanto/lapras.1bpp"
INCBIN "gfx/footprints/kanto/ditto.1bpp"
INCBIN "gfx/footprints/kanto/eevee.1bpp"
INCBIN "gfx/footprints/kanto/vaporeon.1bpp"
INCBIN "gfx/footprints/kanto/jolteon.1bpp"
INCBIN "gfx/footprints/kanto/flareon.1bpp"
INCBIN "gfx/footprints/kanto/porygon.1bpp"
INCBIN "gfx/footprints/kanto/omanyte.1bpp"
INCBIN "gfx/footprints/kanto/omastar.1bpp"
INCBIN "gfx/footprints/kanto/kabuto.1bpp"
INCBIN "gfx/footprints/kanto/kabutops.1bpp"
INCBIN "gfx/footprints/kanto/aerodactyl.1bpp"
INCBIN "gfx/footprints/kanto/snorlax.1bpp"
INCBIN "gfx/footprints/kanto/articuno.1bpp"
INCBIN "gfx/footprints/kanto/zapdos.1bpp"
INCBIN "gfx/footprints/kanto/moltres.1bpp"
INCBIN "gfx/footprints/kanto/dratini.1bpp"
INCBIN "gfx/footprints/kanto/dragonair.1bpp"
INCBIN "gfx/footprints/kanto/dragonite.1bpp"
INCBIN "gfx/footprints/kanto/mewtwo.1bpp"
INCBIN "gfx/footprints/kanto/mew.1bpp"
; Johto
INCBIN "gfx/footprints/johto/chikorita.1bpp"
INCBIN "gfx/footprints/johto/bayleef.1bpp"
INCBIN "gfx/footprints/johto/meganium.1bpp"
INCBIN "gfx/footprints/johto/cyndaquil.1bpp"
INCBIN "gfx/footprints/johto/quilava.1bpp"
INCBIN "gfx/footprints/johto/typhlosion.1bpp"
INCBIN "gfx/footprints/johto/totodile.1bpp"
INCBIN "gfx/footprints/johto/croconaw.1bpp"
INCBIN "gfx/footprints/johto/feraligatr.1bpp"
INCBIN "gfx/footprints/johto/sentret.1bpp"
INCBIN "gfx/footprints/johto/furret.1bpp"
INCBIN "gfx/footprints/johto/hoothoot.1bpp"
INCBIN "gfx/footprints/johto/noctowl.1bpp"
INCBIN "gfx/footprints/johto/ledyba.1bpp"
INCBIN "gfx/footprints/johto/ledian.1bpp"
INCBIN "gfx/footprints/johto/spinarak.1bpp"
INCBIN "gfx/footprints/johto/ariados.1bpp"
INCBIN "gfx/footprints/johto/crobat.1bpp"
INCBIN "gfx/footprints/johto/chinchou.1bpp"
INCBIN "gfx/footprints/johto/lanturn.1bpp"
INCBIN "gfx/footprints/johto/pichu.1bpp"
INCBIN "gfx/footprints/johto/cleffa.1bpp"
INCBIN "gfx/footprints/johto/igglybuff.1bpp"
INCBIN "gfx/footprints/johto/togepi.1bpp"
INCBIN "gfx/footprints/johto/togetic.1bpp"
INCBIN "gfx/footprints/johto/natu.1bpp"
INCBIN "gfx/footprints/johto/xatu.1bpp"
INCBIN "gfx/footprints/johto/mareep.1bpp"
INCBIN "gfx/footprints/johto/flaaffy.1bpp"
INCBIN "gfx/footprints/johto/ampharos.1bpp"
INCBIN "gfx/footprints/johto/bellossom.1bpp"
INCBIN "gfx/footprints/johto/marill.1bpp"
INCBIN "gfx/footprints/johto/azumarill.1bpp"
INCBIN "gfx/footprints/johto/sudowoodo.1bpp"
INCBIN "gfx/footprints/johto/politoed.1bpp"
INCBIN "gfx/footprints/johto/hoppip.1bpp"
INCBIN "gfx/footprints/johto/skiploom.1bpp"
INCBIN "gfx/footprints/johto/jumpluff.1bpp"
INCBIN "gfx/footprints/johto/aipom.1bpp"
INCBIN "gfx/footprints/johto/sunkern.1bpp"
INCBIN "gfx/footprints/johto/sunflora.1bpp"
INCBIN "gfx/footprints/johto/yanma.1bpp"
INCBIN "gfx/footprints/johto/wooper.1bpp"
INCBIN "gfx/footprints/johto/quagsire.1bpp"
INCBIN "gfx/footprints/johto/espeon.1bpp"
INCBIN "gfx/footprints/johto/umbreon.1bpp"
INCBIN "gfx/footprints/johto/murkrow.1bpp"
INCBIN "gfx/footprints/johto/slowking.1bpp"
INCBIN "gfx/footprints/johto/misdreavus.1bpp"
INCBIN "gfx/footprints/johto/unown.1bpp"
INCBIN "gfx/footprints/johto/wobbuffet.1bpp"
INCBIN "gfx/footprints/johto/girafarig.1bpp"
INCBIN "gfx/footprints/johto/pineco.1bpp"
INCBIN "gfx/footprints/johto/forretress.1bpp"
INCBIN "gfx/footprints/johto/dunsparce.1bpp"
INCBIN "gfx/footprints/johto/gligar.1bpp"
INCBIN "gfx/footprints/johto/steelix.1bpp"
INCBIN "gfx/footprints/johto/snubbull.1bpp"
INCBIN "gfx/footprints/johto/granbull.1bpp"
INCBIN "gfx/footprints/johto/qwilfish.1bpp"
INCBIN "gfx/footprints/johto/scizor.1bpp"
INCBIN "gfx/footprints/johto/shuckle.1bpp"
INCBIN "gfx/footprints/johto/heracross.1bpp"
INCBIN "gfx/footprints/johto/sneasel.1bpp"
INCBIN "gfx/footprints/johto/teddiursa.1bpp"
INCBIN "gfx/footprints/johto/ursaring.1bpp"
INCBIN "gfx/footprints/johto/slugma.1bpp"
INCBIN "gfx/footprints/johto/magcargo.1bpp"
INCBIN "gfx/footprints/johto/swinub.1bpp"
INCBIN "gfx/footprints/johto/piloswine.1bpp"
INCBIN "gfx/footprints/johto/corsola.1bpp"
INCBIN "gfx/footprints/johto/remoraid.1bpp"
INCBIN "gfx/footprints/johto/octillery.1bpp"
INCBIN "gfx/footprints/johto/delibird.1bpp"
INCBIN "gfx/footprints/johto/mantine.1bpp"
INCBIN "gfx/footprints/johto/skarmory.1bpp"
INCBIN "gfx/footprints/johto/houndour.1bpp"
INCBIN "gfx/footprints/johto/houndoom.1bpp"
INCBIN "gfx/footprints/johto/kingdra.1bpp"
INCBIN "gfx/footprints/johto/phanpy.1bpp"
INCBIN "gfx/footprints/johto/donphan.1bpp"
INCBIN "gfx/footprints/johto/porygon2.1bpp"
INCBIN "gfx/footprints/johto/stantler.1bpp"
INCBIN "gfx/footprints/johto/smeargle.1bpp"
INCBIN "gfx/footprints/johto/tyrogue.1bpp"
INCBIN "gfx/footprints/johto/hitmontop.1bpp"
INCBIN "gfx/footprints/johto/smoochum.1bpp"
INCBIN "gfx/footprints/johto/elekid.1bpp"
INCBIN "gfx/footprints/johto/magby.1bpp"
INCBIN "gfx/footprints/johto/miltank.1bpp"
INCBIN "gfx/footprints/johto/blissey.1bpp"
INCBIN "gfx/footprints/johto/raikou.1bpp"
INCBIN "gfx/footprints/johto/entei.1bpp"
INCBIN "gfx/footprints/johto/suicune.1bpp"
INCBIN "gfx/footprints/johto/larvitar.1bpp"
INCBIN "gfx/footprints/johto/pupitar.1bpp"
INCBIN "gfx/footprints/johto/tyranitar.1bpp"
INCBIN "gfx/footprints/johto/lugia.1bpp"
INCBIN "gfx/footprints/johto/ho_oh.1bpp"
INCBIN "gfx/footprints/johto/celebi.1bpp"
; Hoenn
INCBIN "gfx/footprints/hoenn/poochyena.1bpp"
INCBIN "gfx/footprints/hoenn/mightyena.1bpp"
INCBIN "gfx/footprints/hoenn/zigzagoon.1bpp"
INCBIN "gfx/footprints/hoenn/linoone.1bpp"
INCBIN "gfx/footprints/hoenn/wingull.1bpp"
INCBIN "gfx/footprints/hoenn/pelipper.1bpp"
INCBIN "gfx/footprints/hoenn/ralts.1bpp"
INCBIN "gfx/footprints/hoenn/kirlia.1bpp"
INCBIN "gfx/footprints/hoenn/gardevoir.1bpp"
INCBIN "gfx/footprints/hoenn/shroomish.1bpp"
INCBIN "gfx/footprints/hoenn/breloom.1bpp"
INCBIN "gfx/footprints/hoenn/nincada.1bpp"
INCBIN "gfx/footprints/hoenn/ninjask.1bpp"
INCBIN "gfx/footprints/hoenn/shedinja.1bpp"
INCBIN "gfx/footprints/hoenn/azurill.1bpp"
INCBIN "gfx/footprints/hoenn/aron.1bpp"
INCBIN "gfx/footprints/hoenn/lairon.1bpp"
INCBIN "gfx/footprints/hoenn/aggron.1bpp"
INCBIN "gfx/footprints/hoenn/carvanha.1bpp"
INCBIN "gfx/footprints/hoenn/sharpedo.1bpp"
INCBIN "gfx/footprints/hoenn/wailmer.1bpp"
INCBIN "gfx/footprints/hoenn/wailord.1bpp"
INCBIN "gfx/footprints/hoenn/numel.1bpp"
INCBIN "gfx/footprints/hoenn/camerupt.1bpp"
INCBIN "gfx/footprints/hoenn/spoink.1bpp"
INCBIN "gfx/footprints/hoenn/grumpig.1bpp"
INCBIN "gfx/footprints/hoenn/spinda.1bpp"
INCBIN "gfx/footprints/hoenn/trapinch.1bpp"
INCBIN "gfx/footprints/hoenn/vibrava.1bpp"
INCBIN "gfx/footprints/hoenn/flygon.1bpp"
INCBIN "gfx/footprints/hoenn/swablu.1bpp"
INCBIN "gfx/footprints/hoenn/altaria.1bpp"
INCBIN "gfx/footprints/hoenn/zangoose.1bpp"
INCBIN "gfx/footprints/hoenn/seviper.1bpp"
INCBIN "gfx/footprints/hoenn/feebas.1bpp"
INCBIN "gfx/footprints/hoenn/milotic.1bpp"
INCBIN "gfx/footprints/hoenn/kecleon.1bpp"
INCBIN "gfx/footprints/hoenn/shuppet.1bpp"
INCBIN "gfx/footprints/hoenn/banette.1bpp"
INCBIN "gfx/footprints/hoenn/duskull.1bpp"
INCBIN "gfx/footprints/hoenn/dusclops.1bpp"
INCBIN "gfx/footprints/hoenn/tropius.1bpp"
INCBIN "gfx/footprints/hoenn/chimecho.1bpp"
INCBIN "gfx/footprints/hoenn/wynaut.1bpp"
INCBIN "gfx/footprints/hoenn/snorunt.1bpp"
INCBIN "gfx/footprints/hoenn/glalie.1bpp"
INCBIN "gfx/footprints/hoenn/spheal.1bpp"
INCBIN "gfx/footprints/hoenn/sealeo.1bpp"
INCBIN "gfx/footprints/hoenn/walrein.1bpp"
INCBIN "gfx/footprints/hoenn/relicanth.1bpp"
INCBIN "gfx/footprints/hoenn/luvdisc.1bpp"
INCBIN "gfx/footprints/hoenn/latias.1bpp"
INCBIN "gfx/footprints/hoenn/latios.1bpp"
; Sinnoh
INCBIN "gfx/footprints/sinnoh/shinx.1bpp"
INCBIN "gfx/footprints/sinnoh/luxio.1bpp"
INCBIN "gfx/footprints/sinnoh/luxray.1bpp"
INCBIN "gfx/footprints/sinnoh/cherubi.1bpp"
INCBIN "gfx/footprints/sinnoh/cherrim.1bpp"
INCBIN "gfx/footprints/sinnoh/ambipom.1bpp"
INCBIN "gfx/footprints/sinnoh/mismagius.1bpp"
INCBIN "gfx/footprints/sinnoh/honchkrow.1bpp"
INCBIN "gfx/footprints/sinnoh/chingling.1bpp"
INCBIN "gfx/footprints/sinnoh/bonsly.1bpp"
INCBIN "gfx/footprints/sinnoh/mime_jr.1bpp"
INCBIN "gfx/footprints/sinnoh/happiny.1bpp"
INCBIN "gfx/footprints/sinnoh/chatot.1bpp"
INCBIN "gfx/footprints/sinnoh/munchlax.1bpp"
INCBIN "gfx/footprints/sinnoh/riolu.1bpp"
INCBIN "gfx/footprints/sinnoh/lucario.1bpp"
INCBIN "gfx/footprints/sinnoh/croagunk.1bpp"
INCBIN "gfx/footprints/sinnoh/toxicroak.1bpp"
INCBIN "gfx/footprints/sinnoh/carnivine.1bpp"
INCBIN "gfx/footprints/sinnoh/finneon.1bpp"
INCBIN "gfx/footprints/sinnoh/lumineon.1bpp"
INCBIN "gfx/footprints/sinnoh/mantyke.1bpp"
INCBIN "gfx/footprints/sinnoh/weavile.1bpp"
INCBIN "gfx/footprints/sinnoh/magnezone.1bpp"
INCBIN "gfx/footprints/sinnoh/lickilicky.1bpp"
INCBIN "gfx/footprints/sinnoh/rhyperior.1bpp"
INCBIN "gfx/footprints/sinnoh/tangrowth.1bpp"
INCBIN "gfx/footprints/sinnoh/electivire.1bpp"
INCBIN "gfx/footprints/sinnoh/magmortar.1bpp"
INCBIN "gfx/footprints/sinnoh/togekiss.1bpp"
INCBIN "gfx/footprints/sinnoh/yanmega.1bpp"
INCBIN "gfx/footprints/sinnoh/leafeon.1bpp"
INCBIN "gfx/footprints/sinnoh/glaceon.1bpp"
INCBIN "gfx/footprints/sinnoh/gliscor.1bpp"
INCBIN "gfx/footprints/sinnoh/mamoswine.1bpp"
INCBIN "gfx/footprints/sinnoh/porygon_z.1bpp"
INCBIN "gfx/footprints/sinnoh/gallade.1bpp"
INCBIN "gfx/footprints/sinnoh/dusknoir.1bpp"
INCBIN "gfx/footprints/sinnoh/froslass.1bpp"
INCBIN "gfx/footprints/sinnoh/rotom.1bpp"
INCBIN "gfx/footprints/sinnoh/phione.1bpp"
INCBIN "gfx/footprints/sinnoh/manaphy.1bpp"
; Other
INCBIN "gfx/footprints/other/ferroseed.1bpp"
INCBIN "gfx/footprints/other/ferrothorn.1bpp"
INCBIN "gfx/footprints/other/stunfisk.1bpp"
INCBIN "gfx/footprints/other/pawniard.1bpp"
INCBIN "gfx/footprints/other/bisharp.1bpp"
INCBIN "gfx/footprints/other/zorua.1bpp"
INCBIN "gfx/footprints/other/zoroark.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp"
; Forms
INCBIN "gfx/footprints/kanto/lapras.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp" ; RATTATA_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; RATICATE_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; RAICHU_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SANDSHREW_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SANDSLASH_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; DIGLETT_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; DUGTRIO_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GRIMER_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MUK_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GEODUDE_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GRAVELER_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GOLEM_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; VULPIX_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; NINETALES_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MAROWAK_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; EXEGGUTOR_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MEOWTH_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; PERSIAN_ALOLA
INCBIN "gfx/footprints/other/placeholder.1bpp" ; PONYTA_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; RAPIDASH_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; FARFETCH_D_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MR__MIME_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; WEEZING_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; ZIGZAGOON_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; LINOONE_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; STUNFISK_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; CORSOLA_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MEOWTH_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SLOWPOKE_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SLOWBRO_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SLOWKING_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; ARTICUNO_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; ZAPDOS_GALAR
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MOLTRES_GALAR
INCBIN "gfx/footprints/kanto/growlithe.1bpp" ; GROWLITHE_HISUI
INCBIN "gfx/footprints/kanto/arcanine.1bpp" ; ARCANINE_HISUI
INCBIN "gfx/footprints/kanto/voltorb.1bpp" ; VOLTORB_HISUI
INCBIN "gfx/footprints/kanto/electrode.1bpp" ; ELECTRODE_HISUI
INCBIN "gfx/footprints/johto/qwilfish.1bpp" ; QWILFISH_HISUI
INCBIN "gfx/footprints/johto/sneasel.1bpp" ; SNEASEL_HISUI
INCBIN "gfx/footprints/other/zorua.1bpp" ; ZORUA_HISUI
INCBIN "gfx/footprints/other/zoroark.1bpp" ; ZOROARK_HISUI
INCBIN "gfx/footprints/other/placeholder.1bpp" ; SLIGGOO_HISUI
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GOODRA_HISUI
INCBIN "gfx/footprints/johto/typhlosion.1bpp" ; TYPHLOSION_HISUI
INCBIN "gfx/footprints/johto/wooper.1bpp" ; WOOPER_PALDEA
INCBIN "gfx/footprints/kanto/tauros.1bpp" ; TAUROS_COMBAT
INCBIN "gfx/footprints/kanto/tauros.1bpp" ; TAUROS_BLAZE
INCBIN "gfx/footprints/kanto/tauros.1bpp" ; TAUROS_AQUA
INCBIN "gfx/footprints/kanto/caterpie.1bpp" ; CATERPIE_VALENCIA
INCBIN "gfx/footprints/kanto/metapod.1bpp" ; METAPOD_VALENCIA
INCBIN "gfx/footprints/kanto/butterfree.1bpp" ; BUTTERFREE_VALENCIA
INCBIN "gfx/footprints/kanto/oddish.1bpp" ; ODDISH_VALENCIA
INCBIN "gfx/footprints/kanto/gloom.1bpp" ; GLOOM_VALENCIA
INCBIN "gfx/footprints/kanto/vileplume.1bpp" ; VILEPLUME_VALENCIA
INCBIN "gfx/footprints/johto/bellossom.1bpp" ; BELLOSSOM_VALENCIA
INCBIN "gfx/footprints/kanto/bellsprout.1bpp" ; BELLSPROUT_VALENCIA
INCBIN "gfx/footprints/kanto/weepinbell.1bpp" ; WEEPINBELL_VALENCIA
INCBIN "gfx/footprints/kanto/victreebel.1bpp" ; VICTREEBEL_VALENCIA
INCBIN "gfx/footprints/kanto/paras.1bpp" ; PARAS_VALENCIA
INCBIN "gfx/footprints/kanto/parasect.1bpp" ; PARASECT_VALENCIA
INCBIN "gfx/footprints/kanto/onix.1bpp" ; ONIX_CRYSTAL
INCBIN "gfx/footprints/johto/steelix.1bpp" ; STEELIX_CRYSTAL
INCBIN "gfx/footprints/johto/ursaring.1bpp" ; URSALUNA_BLOODMOON
INCBIN "gfx/footprints/kanto/dratini.1bpp"
INCBIN "gfx/footprints/kanto/eevee.1bpp"
INCBIN "gfx/footprints/kanto/pikachu.1bpp"
INCBIN "gfx/footprints/kanto/dragonair.1bpp"
INCBIN "gfx/footprints/kanto/dragonite.1bpp"
INCBIN "gfx/footprints/other/placeholder.1bpp" ; ROCKRUFF_OWN_TEMPO
INCBIN "gfx/footprints/other/placeholder.1bpp" ; LYCANROC_MIDNIGHT
INCBIN "gfx/footprints/other/placeholder.1bpp" ; LYCANROC_DUSK
INCBIN "gfx/footprints/other/placeholder.1bpp" ; GIMMIGHOUL_ROAMING
INCBIN "gfx/footprints/other/placeholder.1bpp" ; MEOWTH_ROCKET
    INCBIN "gfx/footprints/sinnoh/rotom.1bpp" ; ROTOM_HEAT
    INCBIN "gfx/footprints/sinnoh/rotom.1bpp" ; ROTOM_WASH
    INCBIN "gfx/footprints/sinnoh/rotom.1bpp" ; ROTOM_FROST
    INCBIN "gfx/footprints/sinnoh/rotom.1bpp" ; ROTOM_FAN
    INCBIN "gfx/footprints/sinnoh/rotom.1bpp" ; ROTOM_MOW
        assert_table_length NUM_POKEMON
